image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - java -jar ./artifacts/app-card-delivery.jar  -port=7777 &
  - chmod +x gradlew

build_script:
  - ./gradlew test --info -Dselenide.headless=true
